<html>
<head>
<title>Exception Handling Concepts in Python</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">Python中的异常处理概念</h1>
<blockquote>原文：<a href="https://pub.towardsai.net/exception-handling-concepts-in-python-4d5116decac3?source=collection_archive---------0-----------------------#2021-04-02">https://pub.towardsai.net/exception-handling-concepts-in-python-4d5116decac3?source=collection_archive---------0-----------------------#2021-04-02</a></blockquote><div><div class="fc ih ii ij ik il"/><div class="im in io ip iq"><h2 id="8358" class="ir is it bd b dl iu iv iw ix iy iz dk ja translated" aria-label="kicker paragraph"><a class="ae ep" href="https://towardsai.net/p/category/programming" rel="noopener ugc nofollow" target="_blank">编程</a></h2><div class=""/><div class=""><h2 id="6648" class="pw-subtitle-paragraph jz jc it bd b ka kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq dk translated">使用try、except和finally关键字进行错误处理</h2></div><figure class="ks kt ku kv gt kw gh gi paragraph-image"><div role="button" tabindex="0" class="kx ky di kz bf la"><div class="gh gi kr"><img src="../Images/2d2fc544c4cd40a17b9a85c68f3fabbc.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*05yBc69N3R2v1te_"/></div></div><figcaption class="ld le gj gh gi lf lg bd b be z dk translated">由<a class="ae lh" href="https://unsplash.com/@markusspiske?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">马库斯·斯皮斯克</a>在<a class="ae lh" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上拍摄的照片</figcaption></figure><p id="c101" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">在本文中，我们将讨论python中的错误处理，用try、except和finally关键字来处理文件和数据管理。</p><p id="4276" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">一般来说，错误分为以下三类:</p><ul class=""><li id="f2f4" class="me mf it lk b ll lm lo lp lr mg lv mh lz mi md mj mk ml mm bi translated">编译时错误:当我们出现一些语法错误时，比如遗漏了什么、拼写错误、使用了未定义的变量等等。这些类型的错误出现在编译时。</li><li id="6da9" class="me mf it lk b ll mn lo mo lr mp lv mq lz mr md mj mk ml mm bi translated"><strong class="lk jd">逻辑错误:</strong>当程序正常运行或编译，但给出错误或不希望的输出时，就会出现这种错误。所以，这种错误被称为逻辑错误。</li><li id="e4fe" class="me mf it lk b ll mn lo mo lr mp lv mq lz mr md mj mk ml mm bi translated"><strong class="lk jd">运行时错误:</strong>该错误发生在程序执行过程中。例如，被零除、编码、I/O或逻辑错误。</li></ul><p id="c6b2" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">异常处理是一种非常现实的处理异常的方法，当程序中发生错误时，解释器会停止并引发一个异常，直到它被处理。为了在程序中处理这些类型的异常以继续执行，我们学习异常处理。</p><div class="ms mt gp gr mu mv"><a rel="noopener  ugc nofollow" target="_blank" href="/python-zero-to-hero-with-examples-c7a5dedb968b"><div class="mw ab fo"><div class="mx ab my cl cj mz"><h2 class="bd jd gy z fp na fr fs nb fu fw jc bi translated">Python:从零到英雄(带示例)</h2><div class="nc l"><h3 class="bd b gy z fp na fr fs nb fu fw dk translated">python初学者手册指南</h3></div><div class="nd l"><p class="bd b dl z fp na fr fs nb fu fw dk translated">pub.towardsai.net</p></div></div><div class="ne l"><div class="nf l ng nh ni ne nj lb mv"/></div></div></a></div><div class="ms mt gp gr mu mv"><a rel="noopener  ugc nofollow" target="_blank" href="/tips-and-tricks-in-machine-learning-with-python-to-avoid-data-leakage-c3908fa4a0c9"><div class="mw ab fo"><div class="mx ab my cl cj mz"><h2 class="bd jd gy z fp na fr fs nb fu fw jc bi translated">使用Python进行机器学习以避免数据泄漏的技巧和诀窍</h2><div class="nc l"><h3 class="bd b gy z fp na fr fs nb fu fw dk translated">更有效地编写机器学习算法</h3></div><div class="nd l"><p class="bd b dl z fp na fr fs nb fu fw dk translated">pub.towardsai.net</p></div></div><div class="ne l"><div class="nk l ng nh ni ne nj lb mv"/></div></div></a></div><h2 id="198a" class="nl nm it bd nn no np dn nq nr ns dp nt lr nu nv nw lv nx ny nz lz oa ob oc iz bi translated">python的例子</h2><pre class="ks kt ku kv gt od oe of og aw oh bi"><span id="bba7" class="nl nm it oe b gy oi oj l ok ol">x = 4<br/>y = 2</span><span id="c0ba" class="nl nm it oe b gy om oj l ok ol">print(x/y)</span><span id="d5c6" class="nl nm it oe b gy om oj l ok ol">#output:<br/>2</span></pre><p id="c341" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">这里，我们得到输出“2 ”,因为执行了print语句。我们还可以打印另一条语句来检查整个程序是否正确执行。</p><pre class="ks kt ku kv gt od oe of og aw oh bi"><span id="405f" class="nl nm it oe b gy oi oj l ok ol">x = 4<br/>y = 2</span><span id="a890" class="nl nm it oe b gy om oj l ok ol">print(x/y)<br/>print("All Well")</span><span id="0102" class="nl nm it oe b gy om oj l ok ol">#output:<br/>2<br/>All Well</span></pre><p id="a60d" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">程序正确执行。如果我们将变量“y”的值改为“0 ”,会发生什么情况？</p><pre class="ks kt ku kv gt od oe of og aw oh bi"><span id="bda1" class="nl nm it oe b gy oi oj l ok ol">x = 4<br/>y = 0</span><span id="595a" class="nl nm it oe b gy om oj l ok ol">print(x/y)<br/>print("All Well")</span><span id="818e" class="nl nm it oe b gy om oj l ok ol">#output:</span><span id="0fde" class="nl nm it oe b gy om oj l ok ol">ZeroDivisionError : division by zero</span></pre><p id="3555" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">该程序给出一个错误，并告诉它不是除以零。还有一点需要注意，第二个打印的语句没有打印出来是因为错误出现在第二个打印的语句之前。</p><p id="a1c7" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">因此，要处理这种错误，可以通过try和except块，如下例所示:</p><pre class="ks kt ku kv gt od oe of og aw oh bi"><span id="4363" class="nl nm it oe b gy oi oj l ok ol">x = 4<br/>y = 0</span><span id="1641" class="nl nm it oe b gy om oj l ok ol">#putting the critical statement in a try block<br/>try:<br/>    print(x/y)</span><span id="647d" class="nl nm it oe b gy om oj l ok ol">#handling the critical statement in except block<br/>except Exception:<br/>    print("You can not divide the number by Zero")</span><span id="5bac" class="nl nm it oe b gy om oj l ok ol">print("All Well")</span><span id="7e10" class="nl nm it oe b gy om oj l ok ol">#output:<br/>You can not divide the number by Zero<br/>All Well</span></pre><p id="ae28" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">上面的例子处理了异常块中的关键语句，程序的执行过程在出错后继续。我们还注意到第二个print语句也被执行了。</p><p id="9bda" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">当没有错误时，将执行try块中的print语句，但不执行异常块。</p><p id="7fd1" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">如果我们想打印错误语句，如下例所示:</p><pre class="ks kt ku kv gt od oe of og aw oh bi"><span id="0e83" class="nl nm it oe b gy oi oj l ok ol">x = 4<br/>y = 0</span><span id="42bd" class="nl nm it oe b gy om oj l ok ol">#putting the critical statement in a try block<br/>try:<br/>    print(x/y)</span><span id="4dc9" class="nl nm it oe b gy om oj l ok ol">#handling the critical statement in except block<br/>except Exception as e:<br/>    print("Error:", e)</span><span id="36cf" class="nl nm it oe b gy om oj l ok ol">print("All Well")</span><span id="0ef2" class="nl nm it oe b gy om oj l ok ol">#output:<br/>Error: division by zero<br/></span></pre><p id="7f63" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">当我们处理文件和数据资源时，关闭它也是非常重要的。下面的例子显示了我们是如何以及在哪个块中关闭文件或资源的。</p><pre class="ks kt ku kv gt od oe of og aw oh bi"><span id="b8a2" class="nl nm it oe b gy oi oj l ok ol">x = 4<br/>y = 0</span><span id="9599" class="nl nm it oe b gy om oj l ok ol">#putting the critical statement in a try block<br/>try:<br/>    print("file opened")   <br/>    print(x/y)<br/>    print("file closed")</span><span id="7e4c" class="nl nm it oe b gy om oj l ok ol">#handling the critical statement in except block<br/>except Exception as e:<br/>    print("Error:", e)</span></pre><p id="5486" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">在这种情况下，我们在try块中打开并关闭了文件，但是如果我们在两者之间得到一个错误，那么执行跳转到异常块，我们的“file closed”语句不会被处理。</p><pre class="ks kt ku kv gt od oe of og aw oh bi"><span id="2667" class="nl nm it oe b gy oi oj l ok ol">#output:<br/>file opened<br/>Error: division by zero</span></pre><p id="2c0d" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">出现错误后，我们的文件仍然打开。如果我们将“文件关闭”语句放在异常块中，那么它将关闭文件。但是，如果我们没有得到一个错误，那么except块不会执行，瓷砖仍然会打开。</p><p id="3fe1" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">为了使文件或资源有错误或无错误地关闭，我们使用finally块。在这个块中，每次执行try或except块后，这个finally块都会执行。因此，我们应该将“文件关闭”语句放在“finally”块中。</p><p id="49d9" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">示例:</p><pre class="ks kt ku kv gt od oe of og aw oh bi"><span id="6ee6" class="nl nm it oe b gy oi oj l ok ol">x = 4<br/>y = 0</span><span id="1deb" class="nl nm it oe b gy om oj l ok ol">#putting critical statement in try block<br/>try:<br/>    print("file opened")   <br/>    print(x/y)    </span><span id="e016" class="nl nm it oe b gy om oj l ok ol">#handling the critical statement in except block<br/>except Exception as e:<br/>    print("Error:", e)</span><span id="1516" class="nl nm it oe b gy om oj l ok ol">finally:<br/>    print("file closed")</span><span id="f49c" class="nl nm it oe b gy om oj l ok ol">#output:<br/>file opened<br/>Error: division by zero<br/>file closed</span></pre><p id="ecde" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">在异常处理程序中使用这三个块是一个好的实践。</p><h2 id="93db" class="nl nm it bd nn no np dn nq nr ns dp nt lr nu nv nw lv nx ny nz lz oa ob oc iz bi translated">结论:</h2><p id="e14e" class="pw-post-body-paragraph li lj it lk b ll on kd ln lo oo kg lq lr op lt lu lv oq lx ly lz or mb mc md im bi translated">当我们测试程序时，这些概念是很方便的。</p><div class="ms mt gp gr mu mv"><a rel="noopener  ugc nofollow" target="_blank" href="/fully-explained-birch-clustering-for-outliers-with-python-2ad6243f126b"><div class="mw ab fo"><div class="mx ab my cl cj mz"><h2 class="bd jd gy z fp na fr fs nb fu fw jc bi translated">用Python对异常值进行BIRCH聚类的完整解释</h2><div class="nc l"><h3 class="bd b gy z fp na fr fs nb fu fw dk translated">聚类中的无监督学习为数据建立树</h3></div><div class="nd l"><p class="bd b dl z fp na fr fs nb fu fw dk translated">pub.towardsai.net</p></div></div><div class="ne l"><div class="os l ng nh ni ne nj lb mv"/></div></div></a></div><p id="2274" class="pw-post-body-paragraph li lj it lk b ll lm kd ln lo lp kg lq lr ls lt lu lv lw lx ly lz ma mb mc md im bi translated">我希望你喜欢这篇文章。通过我的<a class="ae lh" href="https://www.linkedin.com/in/data-scientist-95040a1ab/" rel="noopener ugc nofollow" target="_blank"> LinkedIn </a>和<a class="ae lh" href="https://twitter.com/amitprius" rel="noopener ugc nofollow" target="_blank"> twitter </a>联系我。</p><h1 id="1aad" class="ot nm it bd nn ou ov ow nq ox oy oz nt ki pa kj nw kl pb km nz ko pc kp oc pd bi translated">推荐文章</h1><p id="bf30" class="pw-post-body-paragraph li lj it lk b ll on kd ln lo oo kg lq lr op lt lu lv oq lx ly lz or mb mc md im bi translated"><a class="ae lh" href="https://medium.com/towards-artificial-intelligence/nlp-zero-to-hero-with-python-2df6fcebff6e?sk=2231d868766e96b13d1e9d7db6064df1" rel="noopener"> 1。NLP —零到英雄与Python </a> <br/> 2。<a class="ae lh" href="https://medium.com/towards-artificial-intelligence/python-data-structures-data-types-and-objects-244d0a86c3cf?sk=42f4b462499f3fc3a160b21e2c94dba6" rel="noopener"> Python数据结构数据类型和对象</a>T5】3 .<a class="ae lh" rel="noopener ugc nofollow" target="_blank" href="/data-preprocessing-concepts-with-python-b93c63f14bb6?source=friends_link&amp;sk=5cc4ac66c6c02a6f02077fd43df9681a">数据预处理概念同Python </a> <br/> 4。<a class="ae lh" rel="noopener ugc nofollow" target="_blank" href="/principal-component-analysis-in-dimensionality-reduction-with-python-1a613006d531?source=friends_link&amp;sk=3ed0671fdc04ba395dd36478bcea8a55">用Python进行主成分分析降维</a> <br/> 5。<a class="ae lh" href="https://medium.com/towards-artificial-intelligence/fully-explained-k-means-clustering-with-python-e7caa573176a?source=friends_link&amp;sk=9c5c613ceb10f2d203712634f3b6fb28" rel="noopener">用Python全面讲解K-means聚类</a> <br/> 6。<a class="ae lh" href="https://medium.com/towards-artificial-intelligence/fully-explained-linear-regression-with-python-fe2b313f32f3?source=friends_link&amp;sk=53c91a2a51347ec2d93f8222c0e06402" rel="noopener">用Python </a> <br/> 7全面讲解了线性回归。<a class="ae lh" href="https://medium.com/towards-artificial-intelligence/fully-explained-logistic-regression-with-python-f4a16413ddcd?source=friends_link&amp;sk=528181f15a44e48ea38fdd9579241a78" rel="noopener">用Python </a> <br/>充分解释了Logistic回归8。<a class="ae lh" href="https://medium.com/towards-artificial-intelligence/basic-of-time-series-with-python-a2f7cb451a76?source=friends_link&amp;sk=09d77be2d6b8779973e41ab54ebcf6c5" rel="noopener">用Python实现时间序列的基础知识</a> <br/> 9。<a class="ae lh" rel="noopener ugc nofollow" target="_blank" href="/data-wrangling-with-python-part-1-969e3cc81d69?source=friends_link&amp;sk=9c3649cf20f31a5c9ead51c50c89ba0b">与Python的数据角力—第一部分</a> <br/> 10。<a class="ae lh" href="https://medium.com/analytics-vidhya/confusion-matrix-in-machine-learning-91b6e2b3f9af?source=friends_link&amp;sk=11c6531da0bab7b504d518d02746d4cc" rel="noopener">机器学习中的混淆矩阵</a></p></div></div>    
</body>
</html>